export const TEMP_EMERGENCIES = [
  {
    id: 'emer1',
    type: "Fire",
    location: "123 Main St",
    date: "2024-07-21",
    time: "14:35",
    description: "House fire reported, emergency services on the scene.",
    severity: "High",
  },
  {
    id: 'emer2',
    type: "Medical",
    location: "456 Elm St",
    date: "2024-07-22",
    time: "09:20",
    description: "Heart attack, paramedics en route.",
    severity: "Critical",
  },
  {
    id: 'emer3',
    type: "Accident",
    location: "789 Oak St",
    date: "2024-07-20",
    time: "17:45",
    description: "Car accident with injuries, police and ambulance on site.",
    severity: "Moderate",
  },
  {
    id: 'emer4',
    type: "Fire",
    location: "321 Pine St",
    date: "2024-07-19",
    time: "22:10",
    description: "Commercial building fire, firefighters battling blaze.",
    severity: "High",
  },
  {
    id: 'emer5',
    type: "Medical",
    location: "654 Maple St",
    date: "2024-07-18",
    time: "11:30",
    description: "Severe allergic reaction, EMS responding.",
    severity: "Critical",
  },
  {
    id: 'emer6',
    type: "Accident",
    location: "987 Birch St",
    date: "2024-07-17",
    time: "08:15",
    description: "Multiple car pile-up, emergency services dispatched.",
    severity: "High",
  },
  {
    id: 'emer7',
    type: "Fire",
    location: "231 Cedar St",
    date: "2024-07-16",
    time: "03:50",
    description: "Forest fire, evacuation in progress.",
    severity: "Critical",
  },
  {
    id: 'emer8',
    type: "Medical",
    location: "543 Spruce St",
    date: "2024-07-15",
    time: "13:25",
    description: "Stroke symptoms reported, urgent medical attention required.",
    severity: "Critical",
  },
  {
    id: 'emer9',
    type: "Accident",
    location: "678 Willow St",
    date: "2024-07-14",
    time: "16:00",
    description: "Bicycle accident with serious injuries, ambulance en route.",
    severity: "High",
  },
  {
    id: 'emer10',
    type: "Fire",
    location: "890 Ash St",
    date: "2024-07-13",
    time: "05:45",
    description: "Kitchen fire in apartment building, firefighters on scene.",
    severity: "Moderate",
  },
];
