export const TEMP_JOBS = [
  {
    id: "job1",
    jobRole: "Software Engineer",
    company: "Tech Solutions Inc.",
    typeOfWork: "Remote",
    jobDescription: "Develop and maintain software applications.",
    skillsRequired: ["JavaScript", "Node.js", "React", "MongoDB"],
    lastDateOfApplication: "2024-07-31",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job2",
    jobRole: "Data Scientist",
    company: "Data Analytics Co.",
    typeOfWork: "Hybrid",
    jobDescription: "Analyze complex data sets to derive insights.",
    skillsRequired: ["Python", "Machine Learning", "Statistics", "SQL"],
    lastDateOfApplication: "2024-08-15",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job3",
    jobRole: "Marketing Manager",
    company: "Global Marketing Group",
    typeOfWork: "On-site",
    jobDescription: "Plan and execute marketing campaigns.",
    skillsRequired: [
      "Digital Marketing",
      "Campaign Management",
      "SEO",
      "Analytics",
    ],
    lastDateOfApplication: "2024-07-25",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job4",
    jobRole: "UI/UX Designer",
    company: "Creative Designs Ltd.",
    typeOfWork: "Hybrid",
    jobDescription:
      "Create intuitive user interfaces and engaging user experiences.",
    skillsRequired: ["UI Design", "UX Design", "Adobe XD", "Prototyping"],
    lastDateOfApplication: "2024-08-10",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job5",
    jobRole: "Financial Analyst",
    company: "Finance Experts LLC",
    typeOfWork: "Remote",
    jobDescription: "Analyze financial data and prepare reports.",
    skillsRequired: [
      "Financial Analysis",
      "Accounting",
      "Excel",
      "Forecasting",
    ],
    lastDateOfApplication: "2024-07-28",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job6",
    jobRole: "HR Specialist",
    company: "HR Solutions Corp.",
    typeOfWork: "On-site",
    jobDescription: "Manage recruitment and employee relations.",
    skillsRequired: [
      "Recruitment",
      "Employee Relations",
      "HR Policies",
      "Conflict Resolution",
    ],
    lastDateOfApplication: "2024-08-05",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job7",
    jobRole: "Systems Administrator",
    company: "IT Services Unlimited",
    typeOfWork: "Remote",
    jobDescription: "Maintain and troubleshoot IT systems and networks.",
    skillsRequired: [
      "System Administration",
      "Networking",
      "Linux",
      "Security",
    ],
    lastDateOfApplication: "2024-08-02",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job8",
    jobRole: "Customer Support Representative",
    company: "SupportTech",
    typeOfWork: "Hybrid",
    jobDescription: "Provide timely and effective customer support.",
    skillsRequired: [
      "Customer Service",
      "Problem Solving",
      "Communication",
      "Ticketing Systems",
    ],
    lastDateOfApplication: "2024-07-30",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job9",
    jobRole: "Product Manager",
    company: "Product Innovations Ltd.",
    typeOfWork: "Remote",
    jobDescription: "Define product roadmap and manage product development.",
    skillsRequired: [
      "Product Management",
      "Agile Methodologies",
      "Market Analysis",
      "UX/UI Understanding",
    ],
    lastDateOfApplication: "2024-08-08",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
  {
    id: "job10",
    jobRole: "Sales Executive",
    company: "Sales Pros Inc.",
    typeOfWork: "Hybrid",
    jobDescription: "Generate leads and manage sales pipeline.",
    skillsRequired: [
      "Sales",
      "Negotiation",
      "Client Relationship Management",
      "Prospecting",
    ],
    lastDateOfApplication: "2024-08-12",
    expectedSalary: "50000",
    experience: "2-4 years",
  },
];
